(async function(){
 const canvas=document.getElementById('lamp-canvas'),stage=document.getElementById('stage'),status=document.getElementById('viewer-status'),s=window.neolumeState;
 const gl=canvas.getContext('webgl',{alpha:true,antialias:true,premultipliedAlpha:false});
 function failed(){s.viewerStatus='unavailable';status.textContent=window.neolumeT('unavailable');canvas.style.background='url(lamp-detail.jpg) center / contain no-repeat';for(const id of ['rotate-left','rotate-right','reset-view','light-toggle'])document.getElementById(id).disabled=true}
 if(!gl){failed();return}
 try{
 const vs=`attribute vec3 aPosition; attribute vec3 aNormal; uniform float uYaw; uniform float uPitch; uniform float uAspect; varying vec3 vNormal; varying vec3 vPosition;
 vec3 rotate(vec3 p){float c=cos(uYaw),s=sin(uYaw);p=vec3(c*p.x+s*p.z,p.y,-s*p.x+c*p.z);c=cos(uPitch);s=sin(uPitch);return vec3(p.x,c*p.y-s*p.z,s*p.y+c*p.z);}
 void main(){vec3 p=rotate(aPosition);vNormal=rotate(aNormal);vPosition=p;gl_Position=vec4(p.x/(1.9*uAspect),p.y/1.9,-p.z/10.,1.);}`;
 const fs=`precision mediump float; varying vec3 vNormal; varying vec3 vPosition; uniform vec3 uColor; uniform float uGlow; void main(){vec3 n=normalize(vNormal);if(!gl_FrontFacing)n=-n;float diffuse=max(0.,dot(n,normalize(vec3(-.5,.8,1.))));float rim=pow(1.-abs(n.z),3.)*.09;float spec=pow(max(0.,dot(reflect(-normalize(vec3(-.5,.8,1.)),n),vec3(0.,0.,1.))),28.)*.13;vec3 col=uColor*(.42+diffuse*.75)+vec3(rim+spec);col=mix(col,vec3(1.,.965,.81),uGlow);gl_FragColor=vec4(col,1.);}`;
 function shader(type,source){const sh=gl.createShader(type);gl.shaderSource(sh,source);gl.compileShader(sh);if(!gl.getShaderParameter(sh,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(sh));return sh}
 const program=gl.createProgram();gl.attachShader(program,shader(gl.VERTEX_SHADER,vs));gl.attachShader(program,shader(gl.FRAGMENT_SHADER,fs));gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(program));gl.useProgram(program);
 const loc={};for(const name of ['uYaw','uPitch','uAspect','uColor','uGlow'])loc[name]=gl.getUniformLocation(program,name);const pa=gl.getAttribLocation(program,'aPosition'),na=gl.getAttribLocation(program,'aNormal');gl.enableVertexAttribArray(pa);gl.enableVertexAttribArray(na);gl.enable(gl.DEPTH_TEST);
 const response=await fetch('lamp.json');if(!response.ok)throw Error('Model unavailable');const parts=await response.json(),meshes=[];
 function makeMesh(part,offset=0){const positions=[],normals=[];for(let i=0;i<part.positions.length;i+=3){let [x,y,z]=part.positions.slice(i,i+3),[nx,ny,nz]=part.normals.slice(i,i+3);if(part.kind==='upper'){x=100-x;y=289-y;nx=-nx;ny=-ny}else if(part.kind==='sheets'){[x,z]=[100-z,x];[nx,nz]=[-nz,nx];y+=55+offset}else if(part.kind==='light'){z+=10}else if(part.kind==='cap'){x+=17.2;z+=17.2;y-=1}positions.push((x-50)/100,(y-145)/100,(z-50)/100);normals.push(nx,ny,nz)}const p=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,p);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(positions),gl.STATIC_DRAW);const n=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,n);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(normals),gl.STATIC_DRAW);meshes.push({p,n,count:positions.length/3,kind:part.kind})}
 for(const part of parts){if(part.kind==='sheets'){for(let i=0;i<16;i++)makeMesh(part,i*10.5)}else makeMesh(part)}
 let yaw=-.58,pitch=.10,queued=false,visible=true;
 function color(hex){return [1,3,5].map(i=>parseInt(hex.slice(i,i+2),16)/255)}
 function render(){queued=false;if(!visible)return;const dpr=Math.min(devicePixelRatio||1,2),w=Math.round(canvas.clientWidth*dpr),h=Math.round(canvas.clientHeight*dpr);if(!w||!h)return;if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h}gl.viewport(0,0,w,h);gl.clearColor(0,0,0,0);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.uniform1f(loc.uAspect,w/h);gl.uniform1f(loc.uYaw,yaw);gl.uniform1f(loc.uPitch,pitch);for(const mesh of meshes){gl.bindBuffer(gl.ARRAY_BUFFER,mesh.p);gl.vertexAttribPointer(pa,3,gl.FLOAT,false,0,0);gl.bindBuffer(gl.ARRAY_BUFFER,mesh.n);gl.vertexAttribPointer(na,3,gl.FLOAT,false,0,0);gl.uniform3fv(loc.uColor,color(mesh.kind==='light'?'#e5ddc7':mesh.kind==='sheets'?s.sheets:s.body));gl.uniform1f(loc.uGlow,mesh.kind==='light'&&s.light?.88:0);gl.drawArrays(gl.TRIANGLES,0,mesh.count)}}
 function requestRender(){if(!queued){queued=true;requestAnimationFrame(render)}}
 new ResizeObserver(requestRender).observe(canvas);new IntersectionObserver(entries=>{visible=entries[0].isIntersecting;if(visible)requestRender()}).observe(canvas);
 let pointer=null,lastX=0,lastY=0;canvas.addEventListener('pointerdown',e=>{pointer=e.pointerId;lastX=e.clientX;lastY=e.clientY;canvas.setPointerCapture(pointer)});canvas.addEventListener('pointermove',e=>{if(e.pointerId!==pointer)return;yaw+=(e.clientX-lastX)*.009;if(e.pointerType!=='touch')pitch=Math.max(-.65,Math.min(.65,pitch+(e.clientY-lastY)*.006));lastX=e.clientX;lastY=e.clientY;requestRender()});for(const name of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(name,()=>{pointer=null});canvas.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))return;e.preventDefault();if(e.key==='ArrowLeft')yaw-=.12;if(e.key==='ArrowRight')yaw+=.12;if(e.key==='ArrowUp')pitch=Math.max(-.65,pitch-.08);if(e.key==='ArrowDown')pitch=Math.min(.65,pitch+.08);requestRender()});
 document.getElementById('rotate-left').onclick=()=>{yaw-=.3;requestRender()};document.getElementById('rotate-right').onclick=()=>{yaw+=.3;requestRender()};document.getElementById('reset-view').onclick=()=>{yaw=-.58;pitch=.10;requestRender()};document.getElementById('light-toggle').onclick=()=>{s.light=!s.light;stage.classList.toggle('light-off',!s.light);document.getElementById('light-toggle').setAttribute('aria-pressed',String(s.light));document.querySelector('#light-toggle [data-i18n]').textContent=window.neolumeT(s.light?'lightOn':'lightOff');requestRender()};window.addEventListener('neolume-change',requestRender);canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();failed()});s.viewerStatus='drag';status.textContent=window.neolumeT('drag');requestRender();
 }catch(error){console.error('NeoLume 3D:',error);failed()}
})();
